// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoizhugwcahwhhmqopxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvaXpodWd3Y2Fod2hobXFvcHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NjgzMDAsImV4cCI6MjA1NTA0NDMwMH0.T59pE8pVZnhDnZQ5XSY0wxD5NkaMIwZjS2FTtfSHLkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);